#!/bin/bash

#BAT=$(acpi -b | grep -E -o '[0-9][0-9]?%')

# Full and short texts
#echo "Battery: $BAT"
#echo "BAT: $BAT"

# Set urgent flag below 5% or use orange below 20%
#[ ${BAT%?} -le 5 ] && exit 33
#[ ${BAT%?} -le 20 ] && echo "#FF8000"
if [ "$1" == "--screen" ]
then   
  screen_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

  echo "$screen_brightness"
elif [ "$1" == "--keyboard" ]
then 
  keyboar_brightness=$(cat /sys/class/leds/smc::kbd_backlight/brightness)
  echo "$keyboar_brightness"
else 
  echo "ERROR"
fi;
exit 0
